# Generated by Django 3.1.5 on 2021-01-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20210117_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Provider')], max_length=15),
        ),
        migrations.DeleteModel(
            name='role',
        ),
    ]
