# Generated by Django 3.1.5 on 2021-01-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20210117_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='doxy_link',
            field=models.URLField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
