# Generated by Django 3.1.5 on 2021-01-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20210117_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='deleted',
            field=models.BooleanField(default=True),
        ),
    ]
