# Generated by Django 3.1.5 on 2021-01-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client_note',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
    ]
